# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'ZhiruiWeibo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZhiruiWeibo
  pod 'AFNetworking'
pod 'SDWebImage'
pod 'SnapKit'
pod 'SVProgressHUD'
pod 'YYCache'
pod 'MJRefresh'
#pod 'HYLabel'
#pod 'Alamofire'

end
